# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class SecretApp < Formula
  desc "Testing a private tap."
  homepage "https://github.com/eduardohitek/secret-app"
  version "0.1.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.5/secret-app_0.1.5_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "37d0675cd748122c1fa0e6a2dc3d0df61ad58797091f0a3c44e7930be0eb7568"
    end
    if Hardware::CPU.arm?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.5/secret-app_0.1.5_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c792912378ceed1d7b5585d0cabd43f407f845a66a5543314b4753fb643dabef"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.5/secret-app_0.1.5_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f0f6b9fd17e098b629a518167a5fcdfe461123e0a06e2fbc21c4f457ccd75b2a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.5/secret-app_0.1.5_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3583e6fab8b9cbb94e81ada0b31eef094d7306983cfe65748eb717a0dde944dc"
    end
  end

  def install
    bin.install "secret-app"
  end
end
