# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretApp < Formula
  desc "Testing a private tap."
  homepage "https://github.com/eduardohitek/secret-app"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.3/secret-app_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "67073180564469e862d48539b0621e2cd502b48d0107f20aa477aed61c523c49"
    end
    if Hardware::CPU.arm?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.3/secret-app_0.1.3_Darwin_arm64.tar.gz"
      sha256 "645e28952aa32f1ff2f5feff70f9df14e32a95c533763561e431923d96b67829"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.3/secret-app_0.1.3_Linux_x86_64.tar.gz"
      sha256 "7c2033deabfed190469430e7e56877f5632b31f7fe7fa498ddf601146366af35"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eduardohitek/secret-app/releases/download/v0.1.3/secret-app_0.1.3_Linux_arm64.tar.gz"
      sha256 "f874ce37d0eb1dcfc24635cc86bd0229614a8dd939673f5b7c5c1e9f930ac01f"
    end
  end

  def install
    bin.install "secret-app"
  end
end
